import 'package:fonaco/features/client/leboncoin/models/local_listing_model.dart';

/// Données locales LeBonCoin (fallback + preview UI).
List<LocalListingModel> get devSeedLeBonCoinListings => [
      const LocalListingModel(
        id: 'lbc-art-001',
        name: 'Kouassi Konan — Maçon',
        category: 'artisan',
        categoryLabel: 'Artisan expert',
        specialty: 'Maçon',
        description:
            'Construction résidentielle et commerciale, fondations et finitions.',
        city: 'Cotonou',
        district: 'Ganhi',
        latitude: 6.3654,
        longitude: 2.4183,
        phone: '+22997001234',
        rating: 4.8,
        isFeatured: true,
        tags: ['maçon', 'construction'],
      ),
      const LocalListingModel(
        id: 'lbc-art-002',
        name: 'Aminata Diallo — Électricienne',
        category: 'artisan',
        categoryLabel: 'Artisan expert',
        specialty: 'Électricien',
        description: 'Installations, domotique et panneaux solaires.',
        city: 'Cotonou',
        district: 'Akpakpa',
        latitude: 6.3482,
        longitude: 2.4351,
        phone: '+22997002345',
        rating: 4.9,
        isFeatured: true,
        tags: ['électricité'],
      ),
      const LocalListingModel(
        id: 'lbc-rest-001',
        name: 'Chez Maman — Maquis',
        category: 'restaurant',
        categoryLabel: 'Restaurant',
        specialty: 'Cuisine béninoise',
        description: 'Attiéké, poisson braisé et ambiance conviviale.',
        city: 'Cotonou',
        district: 'Fidjrossè',
        latitude: 6.3578,
        longitude: 2.3912,
        phone: '+22996001122',
        websiteUrl: 'https://example.com/chez-maman',
        rating: 4.6,
        isFeatured: true,
        tags: ['restaurant', 'local'],
      ),
      const LocalListingModel(
        id: 'lbc-rest-002',
        name: 'Le Jardin Secret',
        category: 'restaurant',
        categoryLabel: 'Restaurant',
        specialty: 'Fusion afro',
        description: 'Terrasse ombragée, brunch le week-end.',
        city: 'Cotonou',
        district: 'Cadjehoun',
        latitude: 6.3521,
        longitude: 2.4018,
        websiteUrl: 'https://example.com/jardin-secret',
        rating: 4.7,
        tags: ['brunch', 'terrasse'],
      ),
      const LocalListingModel(
        id: 'lbc-shop-001',
        name: 'Market Bio Cotonou',
        category: 'shop',
        categoryLabel: 'Commerce',
        specialty: 'Épicerie bio',
        description: 'Produits locaux, fruits et légumes frais.',
        city: 'Cotonou',
        district: 'Haie Vive',
        latitude: 6.3712,
        longitude: 2.4288,
        phone: '+22997009988',
        rating: 4.4,
        tags: ['bio', 'courses'],
      ),
      const LocalListingModel(
        id: 'lbc-leisure-001',
        name: 'Plage de Fidjrossè',
        category: 'leisure',
        categoryLabel: 'Loisir / sortie',
        specialty: 'Plage',
        description: 'Promenade en bord de mer, bars et snacks.',
        city: 'Cotonou',
        district: 'Fidjrossè',
        latitude: 6.3475,
        longitude: 2.3855,
        rating: 4.5,
        isFeatured: true,
        tags: ['plage', 'sortie'],
      ),
    ];
